version: 2
updates:
  - package-ecosystem: "npm" # For Node.js projects using npm
    directory: "/" # Location of package manifests (e.g., package.json)
    schedule:
      interval: "monthly" # Check for updates weekly
  
